logging:
  level:
    com.oit.dondok: info

spring:
  datasource:
    driver-class-name: ${DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}
    url: ${MYSQL_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  flyway:
    baseline-on-migrate: false

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: ${REDIS_TIMEOUT:3s}

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:validate}
    properties:
      hibernate:
        format_sql: false
    show-sql: false

management:
  endpoint:
    health:
      show-details: never
