logging:
  level:
    com.oit.dondok: debug
    org.springframework.web.servlet: debug
    org.hibernate.orm.jdbc.bind: trace

spring:
  datasource:
    driver-class-name: ${DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/dondok?serverTimezone=Asia/Seoul&characterEncoding=UTF-8}
    username: ${MYSQL_USER:dondok}
    password: ${MYSQL_PASSWORD:dondok}

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: ${REDIS_TIMEOUT:3s}

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:validate}
    properties:
      hibernate:
        format_sql: true
    show-sql: true

management:
  endpoint:
    health:
      show-details: always

app:
  cookie:
    secure: false
    same-site: Lax
